#!/bin/bash
# Convert all yuv files with numbered name prefix matching argument into jpg files

shopt -s nullglob
FILES="./$1[0-9][0-9].yuv"
for file in $FILES; do
    ffmpeg -v quiet -hide_banner -pixel_format yuv420p -s 1280X720 -i $file -y `basename $file .yuv`.jpg 
done
shopt -u nullglob


